import type { ImportSession } from "@/lib/client/import-session-storage";

export function makeAnalyticsSession(): ImportSession {
  return {
    version: 1,
    savedAt: "2026-06-05T00:00:00.000Z",
    fileName: "sample.csv",
    parserSummary: {
      totalRows: 5,
      parsedRows: 4,
      warningRows: 1,
      errorRows: 1,
      transactionCount: 4,
      warningCount: 2,
      errorCount: 1,
    },
    transactions: [
      {
        id: "tx-1",
        date: "2024-01-15",
        type: "buy",
        asset: "BTC",
        amount: "0.1",
        fiatValue: "4000",
        source: "Binance",
        rawRowNumber: 2,
      },
      {
        id: "tx-2",
        date: "2024-01-20",
        type: "p2p",
        asset: "USDT",
        amount: "5000",
        fiatValue: "5000",
        source: "Binance",
        rawRowNumber: 3,
      },
      {
        id: "tx-3",
        timestamp: "2024-02-01T10:00:00.000Z",
        type: "sell",
        asset: "ETH",
        amount: "1",
        fiatValue: "6000",
        source: "Kraken",
        rawRowNumber: 4,
      },
      {
        id: "tx-4",
        date: "not-a-date",
        type: "unknown",
        asset: "SOL",
        amount: "3",
        fiatValue: null,
        source: "",
        rawRowNumber: 5,
      },
    ],
    parserWarnings: [
      {
        code: "UNKNOWN_TRANSACTION_TYPE",
        message: "Unknown transaction type.",
        rowNumber: 5,
        field: "type",
        severity: "warning",
      },
      {
        code: "INVALID_OPTIONAL_NUMBER",
        message: "Invalid optional number.",
        rowNumber: 5,
        field: "fee",
        severity: "warning",
      },
    ],
    parserErrors: [
      {
        code: "MISSING_REQUIRED_FIELD",
        message: "Missing amount.",
        rowNumber: 6,
        field: "amount",
        severity: "error",
      },
    ],
    rawRows: [
      {
        rowNumber: 2,
        raw: { source: "Binance" },
        normalized: { source: "Binance" },
        status: "ok",
      },
      {
        rowNumber: 3,
        raw: { source: "Binance" },
        normalized: { source: "Binance" },
        status: "ok",
      },
      {
        rowNumber: 4,
        raw: { source: "Kraken" },
        normalized: { source: "Kraken" },
        status: "ok",
      },
      {
        rowNumber: 5,
        raw: { source: "" },
        normalized: { source: "" },
        status: "warning",
      },
      {
        rowNumber: 6,
        raw: { source: "Manual" },
        normalized: { source: "Manual" },
        status: "error",
      },
    ],
    riskResult: {
      findings: [
        {
          id: "risk-missing_cost_basis_basic-ETH-4",
          ruleId: "missing_cost_basis_basic",
          severity: "critical",
          title: "Не найдена история приобретения актива",
          explanation: "Missing cost basis.",
          whyItMatters: "May require explanation.",
          recommendedAction: "Add acquisition history.",
          documentsNeeded: ["acquisition record"],
          affectedTransactionIds: ["tx-3"],
          affectedRawRowNumbers: [4],
          status: "open",
          createdBy: "risk_engine_v1",
        },
        {
          id: "risk-large_p2p_inflow",
          ruleId: "large_p2p_inflow",
          severity: "medium",
          title: "Крупная P2P-операция требует проверки",
          explanation: "P2P inflow.",
          whyItMatters: "May require explanation.",
          recommendedAction: "Add proof.",
          documentsNeeded: ["P2P order proof"],
          affectedTransactionIds: ["tx-2"],
          affectedRawRowNumbers: [3],
          status: "open",
          createdBy: "risk_engine_v1",
        },
        {
          id: "risk-unknown_transaction_type",
          ruleId: "unknown_transaction_type",
          severity: "low",
          title: "Неизвестный тип операции",
          explanation: "Unknown type.",
          whyItMatters: "Review needed.",
          recommendedAction: "Classify manually.",
          documentsNeeded: ["source row"],
          affectedTransactionIds: ["tx-4"],
          affectedRawRowNumbers: [5],
          status: "open",
          createdBy: "risk_engine_v1",
        },
      ],
      summary: {
        totalFindings: 3,
        criticalCount: 1,
        mediumCount: 1,
        lowCount: 1,
        affectedTransactionCount: 3,
        rulesTriggered: [
          "missing_cost_basis_basic",
          "large_p2p_inflow",
          "unknown_transaction_type",
        ],
      },
      readinessScore: 58,
      readinessLabel: "needs_review",
    },
  };
}
