import type { DemoReport } from "@/lib/domain/types";

export const demoReport: DemoReport = {
  id: "demo-source-of-funds-2023-2024",
  title: "Crypto Operations Audit Report",
  status: "demo",
  period: {
    startYear: 2023,
    endYear: 2024,
    label: "2023–2024",
  },
  operationsCount: 184,
  readinessScore: 64,
  riskScore: 64,
  generatedAt: "2026-06-05T00:00:00.000Z",
  metrics: {
    missingCostBasis: 17,
    p2pInflows: 6,
    largeFiatWithdrawals: 4,
    unmatchedTransfers: 3,
    unknownSourceWallets: 2,
  },
  findings: [
    {
      id: "finding-missing-cost-basis",
      ruleId: "missing_cost_basis",
      severity: "critical",
      title: "Не подтверждена себестоимость части активов",
      whatHappened: "В истории есть продажи или выводы активов без видимой записи о покупке или поступлении.",
      whyItMatters: "Банк, бухгалтер или консультант может запросить документы, объясняющие происхождение этих активов.",
      recommendedAction: "Добавьте историю покупок, выписки биржи или пояснение источника поступления активов.",
      documentsNeeded: ["Trade history", "Exchange statement", "Bank statement", "Manual source note"],
      affectedTransactionIds: ["tx-demo-001", "tx-demo-004", "tx-demo-006"],
      count: 17,
    },
    {
      id: "finding-p2p-inflows",
      ruleId: "large_p2p_inflow",
      severity: "medium",
      title: "P2P-поступления требуют пояснения",
      whatHappened: "Обнаружены крупные P2P-поступления USDT за период отчета.",
      whyItMatters: "Такие операции часто требуют понятного описания контрагента, назначения платежа и связанной сделки.",
      recommendedAction: "Подготовьте P2P statement, банковскую выписку и краткое пояснение по каждой крупной операции.",
      documentsNeeded: ["Binance P2P statement", "Bank payment receipt", "Counterparty note"],
      affectedTransactionIds: ["tx-demo-002", "tx-demo-003"],
      count: 6,
    },
    {
      id: "finding-large-fiat-withdrawals",
      ruleId: "large_fiat_withdrawal",
      severity: "medium",
      title: "Крупные выводы в фиат",
      whatHappened: "Найдены крупные выводы средств на банковские счета.",
      whyItMatters: "При проверке банк может сопоставить выводы с историей покупки, продажи и P2P-операций.",
      recommendedAction: "Соберите подтверждение продаж, выписки биржи и банковские документы по выводам.",
      documentsNeeded: ["Withdrawal confirmation", "Exchange sell history", "Bank statement"],
      affectedTransactionIds: ["tx-demo-004"],
      count: 4,
    },
    {
      id: "finding-unmatched-transfers",
      ruleId: "unmatched_transfer",
      severity: "low",
      title: "Не сопоставлены переводы между кошельками",
      whatHappened: "Часть выводов и депозитов выглядит как внутренние переводы, но пары не найдены.",
      whyItMatters: "Без сопоставления такие операции могут выглядеть как неизвестные поступления или выбытия.",
      recommendedAction: "Добавьте адреса кошельков, tx hash и пояснение, что перевод был между собственными счетами.",
      documentsNeeded: ["Wallet address list", "Blockchain transaction link", "Exchange deposit history"],
      affectedTransactionIds: ["tx-demo-005"],
      count: 3,
    },
    {
      id: "finding-unknown-source-wallets",
      ruleId: "unknown_source_wallet",
      severity: "critical",
      title: "Неизвестные кошельки-источники",
      whatHappened: "Есть депозиты с кошельков, которые не отмечены как собственные или известные контрагенты.",
      whyItMatters: "Источник средств может стать главным вопросом при банковской или бухгалтерской проверке.",
      recommendedAction: "Укажите владельца кошелька, добавьте tx hash и документы, подтверждающие происхождение средств.",
      documentsNeeded: ["Wallet ownership note", "Blockchain explorer link", "Source-of-funds explanation"],
      affectedTransactionIds: ["tx-demo-006"],
      count: 2,
    },
  ],
  sampleTransactions: [
    {
      id: "tx-demo-001",
      date: "2023-04-18",
      source: "Binance",
      type: "sell",
      asset: "BTC",
      amount: "0.184",
      fiatValue: "1 742 000 ₽",
      counterparty: null,
      status: "needs_review",
      findingRuleIds: ["missing_cost_basis"],
    },
    {
      id: "tx-demo-002",
      date: "2023-09-07",
      source: "Binance P2P",
      type: "p2p",
      asset: "USDT",
      amount: "12 500",
      fiatValue: "1 187 500 ₽",
      counterparty: "P2P counterparty",
      status: "needs_review",
      findingRuleIds: ["large_p2p_inflow"],
    },
    {
      id: "tx-demo-003",
      date: "2024-01-29",
      source: "Bybit P2P",
      type: "p2p",
      asset: "USDT",
      amount: "8 200",
      fiatValue: "778 000 ₽",
      counterparty: "P2P counterparty",
      status: "needs_review",
      findingRuleIds: ["large_p2p_inflow"],
    },
    {
      id: "tx-demo-004",
      date: "2024-03-14",
      source: "OKX",
      type: "withdrawal",
      asset: "RUB",
      amount: "1 450 000",
      fiatValue: "1 450 000 ₽",
      counterparty: "Bank account",
      status: "needs_review",
      findingRuleIds: ["large_fiat_withdrawal", "missing_cost_basis"],
    },
    {
      id: "tx-demo-005",
      date: "2024-05-22",
      source: "Wallet",
      type: "transfer",
      asset: "ETH",
      amount: "4.2",
      fiatValue: null,
      counterparty: "0x72...19b4",
      status: "missing_data",
      findingRuleIds: ["unmatched_transfer"],
    },
    {
      id: "tx-demo-006",
      date: "2024-10-03",
      source: "External wallet",
      type: "deposit",
      asset: "USDT",
      amount: "18 000",
      fiatValue: null,
      counterparty: "TQ9...7Kc",
      status: "missing_data",
      findingRuleIds: ["unknown_source_wallet", "missing_cost_basis"],
    },
  ],
};
